# Sample: Refinement Only Workflow
# Refines existing BN structures using refiners (e.g., ReactBN)
# See configs/README.md for detailed documentation

workflow: "refinement"

data:
  input_data:
    root: "data"
    dataset: ["asia"]
    source: "bnlearn"
  experiment_data:
    root: "experiments"
    experiment_name: "refinement_only"
    generations: "generations"
    histories: "histories"
    logs: "logs"
    results: "results"
    statistics: "statistics"

observation: 100

refinement:
  data:
    init_generator: "promptbn"
    init_model: "o3-mini"
    source_experiment: "generation_only"
  refiner: "reactbn"
  model: "o3-mini"
