# Sample: Pipeline Workflow
# Runs both generation and refinement in sequence
# See configs/README.md for detailed documentation

workflow: "pipeline"

data:
  input_data:
    root: "data"
    dataset: ["asia"]
    source: "bnlearn"
  experiment_data:
    root: "experiments"
    experiment_name: "unified_pipeline"
    generations: "generations"
    histories: "histories"
    logs: "logs"
    results: "results"
    statistics: "statistics"

observation: 100

generation:
  repeated_run: 3
  generator: "promptbn"
  model: "o3-mini"

refinement:
  data:
    init_generator: "promptbn"
    init_model: "o3-mini"
  refiner: "reactbn"
  model: "o3-mini"
